scripts/database.js
=> database added?

scripts/governors.js
Created a function that returns an html string to display on browser. 
=> created governors HTML

scripts/facilities.js
=> plz actually work

index.html, scripts/governors.js, scripts/main.js
=> Main.JS Wireframe Added

scripts/facilities.js, scripts/governors.js, scripts/main.js
=> Fixed Current Bugs

scripts/main.js
=> fixedagain

scripts/governors.js
=> governer select added

scripts/database.js
=> added maps

scripts/database.js
=> govnamechanged

scripts/facilities.js, scripts/main.js
=> RoughDraftOfFacilityMineralGenerator

scripts/facilities.js
=> Facility JS added

scripts/availableMinerals.js, scripts/facilities.js, scripts/main.js
=> Worked on displaying the options when a option is selected

scripts/colonyMinerals.js, scripts/database.js, scripts/main.js
=> please look

scripts/colonyMinerals.js
=> CurrentlyOnHold

scripts/facilities.js
=> minor change

scripts/availableMinerals.js, scripts/colonyMinerals.js
=> changed names in our for loops

scripts/availableMinerals.js, scripts/colonyMinerals.js, scripts/database.js, scripts/facilities.js, scripts/governors.js, scripts/main.js
Naming conventions and modular issues
text reworks and moving functions to various modules
Serve
=> refactoredModules

scripts/availableMinerals.js, scripts/main.js, styles/main.css
=> adjusted css

scripts/SpacePurchase.js, scripts/main.js
=> PurchaseDisplayShow

scripts/availableMinerals.js, scripts/main.js, styles/main.css
=> Made Styling Changes

scripts/SpacePurchase.js, scripts/database.js, scripts/main.js
=> Getting CSS

styles/main.css
=> Fixed the width of the purchase button
